name: Booking and Analytics Service CI
on:
  push:
    paths:
      - 'booking-analytics-service/**'
  pull_request:
    paths:
      - 'booking-analytics-service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('booking-analytics-service/go.sum') }}
          restore-keys: |
            go-

      - name: Download dependencies
        run: |
          cd booking-analytics-service
          go mod download
      - name: Run tests
        run: |
          cd booking-analytics-service
          go test ./... -v

  #      - name: Build binary (sanity check)
  #        run: |
  #          cd booking-analytics-service
  #          go build ./...
  #
  #      - name: Build Docker image
  #        run: docker build -t booking-analytics-service ./booking-analytics-service


