name: Mobile API Gateway CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./mobile-api-gateway
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mobile-api-gateway:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mobile-api-gateway:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mobile-api-gateway:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mobile-api-gateway:buildcache,mode=max